import pandas as pd
configfile: "config/config.yaml"
samples = pd.read_table(config["samples"], index_col = "sample")

rule all:
    input:
        expand("results/stats/{sample}_aug.txt", sample = list(samples.index))

include: "rules/bowtie.smk"
include: "rules/samtools.smk"